# Generated by Django 6.0.1 on 2026-01-19 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='products/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('product_model', models.CharField(blank=True, max_length=100, null=True)),
                ('available_size', models.CharField(blank=True, help_text='e.g., S, M, L, XL or 10, 11, 12', max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('stock', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Product')),
                ('is_on_sale', models.BooleanField(default=False, verbose_name='Price Off Product')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='myapp.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
